### ISSUE TITLE
56行提示device变量未定义，也许不是内置变量

### ISSUE THREAD

**Issue by xuzheliang135** [congwulong/alipay_autojs#1]

**Comment by congwulong** [comment]
> _No description provided._

应该是auto.js版本的问题，你现在版本是多少？Android版本是多少？有没有开启无障碍服务？

**Comment by xuzheliang135** [comment]
auto.js 版本：2.0.16 beta2
Android版本： MIUI 10.3.4 Android 8.1.0
开了无障碍
我注释掉unlock之后，他也不能运行，会在foreach那里出错

**Comment by congwulong** [comment]
> auto.js 版本：2.0.16 beta2
> Android版本： MIUI 10.3.4 Android 8.1.0
> 开了无障碍
> 我注释掉unlock之后，他也不能运行，会在foreach那里出错

auto.js版本太低了，现在最新都是4了
