### ISSUE TITLE
为什么没有自动收取

### ISSUE THREAD

**Issue by jasonyun** [congwulong/alipay_autojs#11]
手机上在动，可以进去之后并没有做收取的操作？？请问是怎么回事？

**Comment by congwulong** [comment]
程序收取点击很快，看不到的。可以看自己能量收取记录，自己能量有没有增加？

**Comment by jasonyun** [comment]
没有增加

**Comment by Tfancy** [comment]
请问下要怎么操作啊？把js文件放在手机随便一个文件夹就可以自动进行了吗？
