### ISSUE TITLE
弹窗怎么自动打开

### ISSUE THREAD

**Issue by booldplx** [congwulong/alipay_autojs#12]
Auto.js将开始截取您的屏幕上显示的所有内容这个弹窗怎么自动开始呢？还有大佬，这个是每天在startTime自动运行么？我关闭屏幕了能运行么？求解答 谢谢

**Comment by booldplx** [comment]
auto.js最新版本，我下载代码编译安装的

**Comment by congwulong** [comment]
> Auto.js将开始截取您的屏幕上显示的所有内容这个弹窗怎么自动开始呢？还有大佬，这个是每天在startTime自动运行么？我关闭屏幕了能运行么？求解答 谢谢

对不起，我这里只负责脚本，关于手机弹窗设置以及解锁技巧靠您自己了。
