### ISSUE TITLE
好像还是不行呢

### ISSUE THREAD

**Issue by fgzong** [congwulong/alipay_autojs#17]
还是识别不了好友能量，难道是我手机问题？我把1045左右改了改，也不管用…

**Comment by congwulong** [comment]
> 还是识别不了好友能量，难道是我手机问题？我把1045左右改了改，也不管用…

你可以找一个带收能量小手的截图给我看看？congwulong@outlook.com. 我来分析下。

**Comment by fgzong** [comment]
我给你发了邮件啦，谢谢！！
