### ISSUE TITLE
收能量有遗漏

### ISSUE THREAD

**Issue by OpenWaygate** [congwulong/alipay_autojs#18]
排行榜里如果两个连续的好友有能量, 在收完前一个后页面下滑会漏掉第二个, 向下滑到底部后不会再向上滑重新寻找.

**Comment by congwulong** [comment]
> 排行榜里如果两个连续的好友有能量, 在收完前一个后页面下滑会漏掉第二个, 向下滑到底部后不会再向上滑重新寻找.

已更新，感谢反馈
