### ISSUE TITLE
小米8，miui10调不出输入密码页面是什么情况

### ISSUE THREAD

**Issue by ytianzaishui** [congwulong/alipay_autojs#5]

**Comment by congwulong** [comment]
unlock()函数里面：
swipe(500, 0, 500, 1900, 2000); //从坐标(500,0)下滑到(500,1900)，用时2s
 click(100,150); //单击时间
需要根据你的分辨率修改一下坐标。

**Comment by haofengsiji** [comment]
是不是所有function里的跟坐标有关系的全部都要调？
