### ISSUE TITLE
Type Error:Cannot find function findMulticColors in object[object Object)(<alipay_auto>#184)

### ISSUE THREAD

**Issue by ChasterXia** [congwulong/alipay_autojs#8]
![S00212-07365765](https://user-images.githubusercontent.com/60947908/74289620-8b782380-4d6a-11ea-8c8e-c930741b5b5c.png)
Type Error:Cannot find function findMulticColors in object[object Object)(<alipay_auto>#184)

**Comment by congwulong** [comment]
你的auto.js版本是多少？

**Comment by ChasterXia** [comment]
> 你的auto.js版本是多少？

Version3.0.0Alpha40
![S00213-12512794](https://user-images.githubusercontent.com/60947908/74402618-b98b5f80-4e5f-11ea-9778-d3b5862f19e7.png)

**Comment by congwulong** [comment]
> > 你的auto.js版本是多少？
> 
> Version3.0.0Alpha40
> ![S00213-12512794](https://user-images.githubusercontent.com/60947908/74402618-b98b5f80-4e5f-11ea-9778-d3b5862f19e7.png)

版本太低了哦，下载4.0及以上吧，网上搜一搜
