### ISSUE TITLE
大佬请教下，万分感谢，代码改好后亮屏状态运行，程序直接跳过时间校验就进支付宝操作了，无法做到定时，然后用autojs自带的定时任务设定好程序开始运行时间后，可以完成屏幕解锁但之后程序又不运行了，检查程序实在找不到错误，求指导，autojs版本4.1.1的

### ISSUE THREAD

**Issue by huangknow** [congwulong/alipay_autojs#9]

**Comment by congwulong** [comment]
"代码改好后亮屏状态运行，程序直接跳过时间校验就进支付宝操作了，无法做到定时"
--> 你的意思是程序里的startTime和endTime吧，这两个时间代表程序循环收取能量的时间。超出这个时间程序也会运行，只是收一次能量就结束。

"autojs自带的定时任务设定好程序开始运行时间后，可以完成屏幕解锁但之后程序又不运行了"
--> 再复现一遍后，打开auto.js然后看看程序的Log，停在哪里了？

**Comment by huangknow** [comment]
" 你的意思是程序里的startTime和endTime吧，这两个时间代表程序循环收取能量的时间。超出这个时间程序也会运行，只是收一次能量就结束。  "
-->是的，不在这个时间范围内运行的话他会收能量一次，然后就结束了，但一直在后台，到了我设定的时间范围内程序不会亮屏启动。
"再复现一遍后，打开auto.js然后看看程序的Log，停在哪里了？"
-->解锁亮屏后手机页面停在设置闹钟，然后log里停在   "开始运行【/storage/emulated/0/脚本/alipay_auto.js】"    然后就没后续了，程序就不动了。

谢谢大佬回复

**Comment by congwulong** [comment]
" 你的意思是程序里的startTime和endTime吧，这两个时间代表程序循环收取能量的时间。超出这个时间程序也会运行，只是收一次能量就结束。 "
-->是的，不在这个时间范围内运行的话他会收能量一次，然后就结束了，但一直在后台，到了我设定的时间范围内程序不会亮屏启动。
-->这个问题应该是要给auto.js所有的权限，在手机设置中设置一下试试

"再复现一遍后，打开auto.js然后看看程序的Log，停在哪里了？"
-->解锁亮屏后手机页面停在设置闹钟，然后log里停在 "开始运行【/storage/emulated/0/脚本/alipay_auto.js】" 然后就没后续了，程序就不动了。
-->原因同上，也是需要给予所有权限。autojs的版本4.1.1可以自动收能量，但是timer有问题

**Comment by huangknow** [comment]
谢谢大佬！重新去看了下权限，全部打开了，这下可以正常运行了。
